name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install

    - name: lint
      run: make lint
      
    - name: Test with pytest
      run: make test
    
    - name: Format
      run: make format
    
    
